# Generated by Django 2.1.4 on 2019-02-27 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this object should be enabled.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True)),
                ('key', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JsonParser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this object should be enabled.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True)),
                ('app', models.CharField(max_length=8)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parsing.Field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogSample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this object should be enabled.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True)),
                ('value', models.TextField()),
                ('object_id', models.BigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_logsample_related', related_query_name='parsing_logsamples', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegexParser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this object should be enabled.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True)),
                ('app', models.CharField(max_length=8)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parsing.Field')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
