# Generated by Django 2.1.4 on 2019-02-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20190117_2325'),
        ('parsing', '0002_auto_20190227_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonparser',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regexparser',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Token'),
            preserve_default=False,
        ),
    ]
