# Generated by Django 2.1.4 on 2019-02-27 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20190117_2325'),
        ('parsing', '0003_auto_20190227_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this object should be enabled.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True)),
                ('key', models.CharField(max_length=8)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Token')),
            ],
        ),
        migrations.RemoveField(
            model_name='jsonparser',
            name='app',
        ),
        migrations.RemoveField(
            model_name='jsonparser',
            name='token',
        ),
        migrations.RemoveField(
            model_name='regexparser',
            name='app',
        ),
        migrations.RemoveField(
            model_name='regexparser',
            name='token',
        ),
        migrations.AlterField(
            model_name='jsonparser',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.Field'),
        ),
        migrations.AlterField(
            model_name='regexparser',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.Field'),
        ),
        migrations.AddField(
            model_name='jsonparser',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsing.Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regexparser',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsing.Service'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('token', 'key')},
        ),
    ]
