# Generated by Django 2.1.4 on 2019-02-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_auto_20190227_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegexParser',
            new_name='Parser',
        ),
        migrations.RemoveField(
            model_name='jsonparser',
            name='field',
        ),
        migrations.RemoveField(
            model_name='jsonparser',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='parser',
            options={'ordering': ('field', 'priority')},
        ),
        migrations.RemoveField(
            model_name='logsample',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='logsample',
            name='object_id',
        ),
        migrations.AddField(
            model_name='logsample',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsing.Service'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JsonParser',
        ),
    ]
