# Generated by Django 2.1.4 on 2019-02-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_auto_20190227_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogSample',
            new_name='Sample',
        ),
    ]
