# Generated by Django 2.1.4 on 2019-02-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0006_auto_20190227_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Token'),
        ),
    ]
