# Generated by Django 2.1.4 on 2019-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0007_auto_20190227_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='parser',
            name='benchmark',
            field=models.FloatField(default=0.0),
        ),
    ]
