# Generated by Django 2.1.4 on 2019-02-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_auto_20190227_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Whether or not this object should be enabled.'),
        ),
    ]
