# Generated by Django 2.1.4 on 2019-02-27 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0009_auto_20190227_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this object should be enabled.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True)),
                ('value', models.CharField(max_length=64)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing.Field')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='parsing.Sample')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assertion',
            unique_together={('sample', 'key')},
        ),
    ]
