# Generated by Django 2.1.4 on 2019-02-28 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0010_auto_20190227_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertion',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parser',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsers', to='parsing.Service'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='parsing.Service'),
        ),
    ]
