# Generated by Django 2.1.4 on 2019-02-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0011_auto_20190228_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
