# Generated by Django 2.1.4 on 2019-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0012_sample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='validator',
            field=models.TextField(default='(.*)', help_text='Regex string to apply against parsed value to detect match.'),
        ),
    ]
