# Generated by Django 2.1.4 on 2019-03-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0016_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('str', 'String'), ('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('IPAddress', 'IP Address'), ('list', 'List/Array'), ('dict', 'Dict/Hash')], default='str', max_length=16),
        ),
    ]
