# Generated by Django 2.1.3 on 2018-11-26 22:14

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255),
        ),
    ]
