# Generated by Django 2.1.3 on 2018-11-29 00:10

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20181126_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='owner',
        ),
        migrations.AddField(
            model_name='token',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
