# Generated by Django 2.1.3 on 2018-11-29 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20181129_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether or not this object should be enabled.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of last object modification.'),
        ),
        migrations.AlterField(
            model_name='token',
            name='application',
            field=models.ForeignKey(help_text='What business process or application is this token designed to support?', on_delete=django.db.models.deletion.PROTECT, to='common.Application'),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.'),
        ),
        migrations.AlterField(
            model_name='token',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether or not this object should be enabled.'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of token expiration.'),
        ),
        migrations.AlterField(
            model_name='token',
            name='owners',
            field=models.ManyToManyField(help_text='What user(s) are responsible for the logs submitted using this token?', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of last object modification.'),
        ),
        migrations.AlterField(
            model_name='token',
            name='value',
            field=models.CharField(default=uuid.uuid4, help_text='Token string, as UUID4.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether or not this object should be enabled.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of last object modification.'),
        ),
    ]
