# Generated by Django 2.1.3 on 2018-11-29 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20181129_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of object creation.')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of last object modification.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this object should be enabled.')),
                ('hostname', models.CharField(help_text='Name of a specific computer or host on the network.', max_length=255)),
                ('domain', models.CharField(help_text='The domain name a specific computer, or host, on the network is associated with.', max_length=255)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='value',
            field=models.CharField(default='Default', help_text='Name of the application or business process.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('hostname', 'domain')},
        ),
        migrations.AddField(
            model_name='application',
            name='hosts',
            field=models.ManyToManyField(help_text='Hostnames or FQDNs identifying this application/process.', to='common.Host'),
        ),
    ]
