# Generated by Django 2.1.3 on 2018-12-10 17:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20181129_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='application',
        ),
        migrations.AddField(
            model_name='token',
            name='hosts',
            field=models.ManyToManyField(help_text='What hostnames to expect logs from using this token.', to='common.Host'),
        ),
    ]
