# Generated by Django 2.1.3 on 2018-12-10 17:35

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20181210_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='hosts',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='owners',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(default=common.models.get_expiration, help_text='Date and time of token expiration.'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
