# Generated by Django 2.1.4 on 2018-12-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_pulse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
