# Generated by Django 2.1.4 on 2018-12-21 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20181221_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='users',
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(default=1, help_text='What user is responsible for the creation of this token?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
