# Generated by Django 2.1.4 on 2018-12-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20181221_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='notes',
            field=models.CharField(blank=True, help_text='Any notes about the reason for this token.', max_length=160, null=True),
        ),
    ]
