# Generated by Django 2.1.4 on 2018-12-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20181221_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='host',
            name='tags',
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True),
        ),
        migrations.RemoveField(
            model_name='pulse',
            name='tags',
        ),
        migrations.AddField(
            model_name='pulse',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True),
        ),
        migrations.RemoveField(
            model_name='token',
            name='tags',
        ),
        migrations.AddField(
            model_name='token',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of any custom tags related to this object.', max_length=160, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
