# Generated by Django 2.1.4 on 2018-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20181221_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of any custom tags related to this object.', max_length=160),
        ),
        migrations.AlterField(
            model_name='host',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.'),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of any custom tags related to this object.', max_length=160),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.'),
        ),
        migrations.AlterField(
            model_name='token',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of any custom tags related to this object.', max_length=160),
        ),
        migrations.AlterField(
            model_name='token',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of any custom tags related to this object.', max_length=160),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of last object modification.'),
        ),
    ]
