# Generated by Django 2.1.4 on 2018-12-21 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20181221_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='value',
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default=uuid.uuid4, help_text='Token string, as UUID4.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
