# Generated by Django 2.1.4 on 2018-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20181221_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='retention',
            field=models.PositiveIntegerField(default=365, help_text='How long (in days) to keep logs submitted under this token.'),
        ),
    ]
