# Generated by Django 2.1.4 on 2019-01-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_token_retention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='retention',
            new_name='retain',
        ),
    ]
