# Generated by Django 2.1.4 on 2019-01-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_pulse_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='backup_email',
            field=models.EmailField(blank=True, default='', help_text='Email address of a second party or group to send expiration warnings to.', max_length=254),
        ),
    ]
